# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1bd703bd8f3dafdef0a806e1d5a72722fd37d4c73d2d281ed87a6d8eb4488aa38eb5a696371bde365dd30546bd676a07d26d2d92517f528dc8873578b35ed4

test:
  secret_key_base: c72e20c2d83663380dae2de42432dbc049c72e1c0c111497c2b591e68de013150b3b919ddb3cb95b29b4e636ca0e8bee4936f7d3bf59501a8fd5297ac6696f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
